SELECT * FROM Negocio  
SELECT * FROM DetalleVenta 
SELECT * FROM Venta  
SELECT * FROM VentaNumeroCorrelativo  
SELECT * FROM Cliente 
SELECT * FROM TipoDocumento 
SELECT * FROM Producto  
SELECT * FROM Categoria 
SELECT * FROM Medida  
SELECT * FROM Moneda   
SELECT * FROM UsuarioRestableceContrasenia 
SELECT * FROM UsuarioContrasena 
SELECT * FROM UsuarioId  	
SELECT * FROM Usuario  
SELECT * FROM Genero  
SELECT * FROM MenuRol  
SELECT * FROM Menu  
SELECT * FROM Rol
SELECT * FROM Marca

