//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de Suscripción {0} del usuario: {1}.
        /// </summary>
        public static string BitacoraCuenta {
            get {
                return ResourceManager.GetString("BitacoraCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización  de la suscripción {0} a la nueva suscripción {1} del usuario {2}.
        /// </summary>
        public static string BitacoraCuentaActualizacion {
            get {
                return ResourceManager.GetString("BitacoraCuentaActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de Cuenta Gratuita del usuario: {0}.
        /// </summary>
        public static string BitacoraCuentaGratuita {
            get {
                return ResourceManager.GetString("BitacoraCuentaGratuita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelación de la Suscripción {0} del usuario: {1}.
        /// </summary>
        public static string CancelacionSuscripcion {
            get {
                return ResourceManager.GetString("CancelacionSuscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la categoría porque tiene gastos asociados.
        /// </summary>
        public static string ExistGastoCategoria {
            get {
                return ResourceManager.GetString("ExistGastoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el método de pago porque tiene gastos asociados.
        /// </summary>
        public static string ExistGastoMetodoPago {
            get {
                return ResourceManager.GetString("ExistGastoMetodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la categoría porque tiene ingresos asociados.
        /// </summary>
        public static string ExistIngresoCategoria {
            get {
                return ResourceManager.GetString("ExistIngresoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando creación de cuenta del usuario: {0}. Validando datos....
        /// </summary>
        public static string LogInicioRegistroUsuario {
            get {
                return ResourceManager.GetString("LogInicioRegistroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creó el usuario: {0}.
        /// </summary>
        public static string LogRegistroUsuarioExito {
            get {
                return ResourceManager.GetString("LogRegistroUsuarioExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obteniendo data - ParametroService.GetAllAsync.
        /// </summary>
        public static string ParametroService_GetAllAsyncRequest {
            get {
                return ResourceManager.GetString("ParametroService_GetAllAsyncRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data obtenida correctamente - ParametroService.GetAllAsync.
        /// </summary>
        public static string ParametroService_GetAllAsyncSuccess {
            get {
                return ResourceManager.GetString("ParametroService_GetAllAsyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu registro ha sido un éxito. ¡Bienvenido! Ahora eres parte de nuestra comunidad. .
        /// </summary>
        public static string SuccessAddUser {
            get {
                return ResourceManager.GetString("SuccessAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La contraseña se ha actualizado correctamente!.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de moneda realizado correctamente.
        /// </summary>
        public static string SuccessCurrencyChange {
            get {
                return ResourceManager.GetString("SuccessCurrencyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo enviado correctamente al usuario {0}.
        /// </summary>
        public static string SuccessEmailTransaction {
            get {
                return ResourceManager.GetString("SuccessEmailTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de verificación que acabamos de enviarte por correo a &lt;br&gt; &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SuccessOTPGeneradoCorrectamente {
            get {
                return ResourceManager.GetString("SuccessOTPGeneradoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu correo ha sido verificado, continúa con el registro de tus datos personales y tus preferencias..
        /// </summary>
        public static string SuccessOTPVerificado {
            get {
                return ResourceManager.GetString("SuccessOTPVerificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Éxito!.
        /// </summary>
        public static string SuccessTitleTransaction {
            get {
                return ResourceManager.GetString("SuccessTitleTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te enviamos un mensaje con instrucciones para restablecer la contraseña a &lt;br&gt; &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SuccessTokenOlvideContraseniaGeneradoCorrectamente {
            get {
                return ResourceManager.GetString("SuccessTokenOlvideContraseniaGeneradoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación se ha realizado correctamente..
        /// </summary>
        public static string SuccessTransaction {
            get {
                return ResourceManager.GetString("SuccessTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su información ha sido actualizada correctamente, vuelva a iniciar sesión.
        /// </summary>
        public static string SuccessUpdateUser {
            get {
                return ResourceManager.GetString("SuccessUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TokenActualizado.
        /// </summary>
        public static string TokenActualizado {
            get {
                return ResourceManager.GetString("TokenActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TokenExpirado.
        /// </summary>
        public static string TokenExpirado {
            get {
                return ResourceManager.GetString("TokenExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token validado correctamente.
        /// </summary>
        public static string TokenValidado {
            get {
                return ResourceManager.GetString("TokenValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu correo ha sido verificado correctamente..
        /// </summary>
        public static string ValidOTPVerificado {
            get {
                return ResourceManager.GetString("ValidOTPVerificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una cuenta para este correo electrónico.
        /// </summary>
        public static string WarningNoExisteUsuario {
            get {
                return ResourceManager.GetString("WarningNoExisteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación expirado, solicitar nuevo código..
        /// </summary>
        public static string WarningOTPCaducado {
            get {
                return ResourceManager.GetString("WarningOTPCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su código de verificación es incorrecto, vuelva a intentarlo.
        /// </summary>
        public static string WarningOTPNoExiste {
            get {
                return ResourceManager.GetString("WarningOTPNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Advertencia!.
        /// </summary>
        public static string WarningTitleTransaction {
            get {
                return ResourceManager.GetString("WarningTitleTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El enlace de restablecimiento de contraseña no es válido.
        /// </summary>
        public static string WarningTokenOlvideContraseniaNoValido {
            get {
                return ResourceManager.GetString("WarningTokenOlvideContraseniaNoValido", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El enlace de restablecimiento de contraseña no es válido.
        /// </summary>
        public static string WarningUsuarioNoActivo
        {
            get
            {
                return ResourceManager.GetString("WarningUsuarioNoActivo", resourceCulture);
            }
        }

    }
}
