//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DictionaryErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictionaryErrors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource.DictionaryErrors", typeof(DictionaryErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no debe ser igual al correo electrónico.
        /// </summary>
        public static string AccesoEqualCorreo {
            get {
                return ResourceManager.GetString("AccesoEqualCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada no cumple con los requisitos de seguridad: &lt;/br&gt;
        ///- Longitud mínima: 12 caracteres. &lt;/br&gt;
        ///- Debe contener una letra en mayúsculas. &lt;/br&gt;
        ///- Debe contener una letra en minúsculas. &lt;/br&gt;
        ///- Debe poseer un caracter numérico. 
        ///- Un símbolo especial.
        /// </summary>
        public static string AutenticacionValidacionContrasenia {
            get {
                return ResourceManager.GetString("AutenticacionValidacionContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no cumple con los requisitos. &lt;/br&gt;
        ///- Longitud mínima: 12 caracteres. &lt;/br&gt;
        ///- Longitud máxima 40 caracteres..
        /// </summary>
        public static string AutenticacionValidacionUsuario {
            get {
                return ResourceManager.GetString("AutenticacionValidacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que has ingresado no coincide con la actual. Inténtelo de nuevo..
        /// </summary>
        public static string ClaveActualIncorrecta {
            get {
                return ResourceManager.GetString("ClaveActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string ClaveIncorrecta {
            get {
                return ResourceManager.GetString("ClaveIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo ya registrado.
        /// </summary>
        public static string CorreoRegistrado {
            get {
                return ResourceManager.GetString("CorreoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar el cambio de moneda.
        /// </summary>
        public static string CurrencyTransaction {
            get {
                return ResourceManager.GetString("CurrencyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar la operación. Tiene ingresos registrados .
        /// </summary>
        public static string ErrorExisteIngresosConCategoria {
            get {
                return ResourceManager.GetString("ErrorExisteIngresosConCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad no existe.
        /// </summary>
        public static string ErrorNoExiste {
            get {
                return ResourceManager.GetString("ErrorNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups!.
        /// </summary>
        public static string ErrorTitleTransaction {
            get {
                return ResourceManager.GetString("ErrorTitleTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar la operación. Por favor, contacta al soporte técnico.
        /// </summary>
        public static string ErrorTransaction {
            get {
                return ResourceManager.GetString("ErrorTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ya se encuentra registrado en el sistema.
        /// </summary>
        public static string ExistCorreo {
            get {
                return ResourceManager.GetString("ExistCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra registrado en el sistema.
        /// </summary>
        public static string ExistUsuario {
            get {
                return ResourceManager.GetString("ExistUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario tiene un plan no registrado en el sistema.
        /// </summary>
        public static string IdPlanNoExiste {
            get {
                return ResourceManager.GetString("IdPlanNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No podemos encontrar una cuenta con los datos ingresados. Reinténtalo.
        /// </summary>
        public static string UsuarioNoRegistrado {
            get {
                return ResourceManager.GetString("UsuarioNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UsuarioRegistrado.
        /// </summary>
        public static string UsuarioRegistrado {
            get {
                return ResourceManager.GetString("UsuarioRegistrado", resourceCulture);
            }
        }
    }
}
