//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parameters() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource.Parameters", typeof(Parameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GSCT001.
        /// </summary>
        public static string CodigoGastoCategoriaDefecto {
            get {
                return ResourceManager.GetString("CodigoGastoCategoriaDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INCT001.
        /// </summary>
        public static string CodigoIngresoCategoriaDefecto {
            get {
                return ResourceManager.GetString("CodigoIngresoCategoriaDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MPCT001.
        /// </summary>
        public static string CodigoMetodosPagoCategoriaDefecto {
            get {
                return ResourceManager.GetString("CodigoMetodosPagoCategoriaDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        public static string dd_mm_yyyy {
            get {
                return ResourceManager.GetString("dd_mm_yyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm:ss.
        /// </summary>
        public static string dd_MM_yyyy_HH_mm_ss {
            get {
                return ResourceManager.GetString("dd_MM_yyyy_HH_mm_ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        public static string IdCuentaBasica {
            get {
                return ResourceManager.GetString("IdCuentaBasica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        public static string IdCuentaEstandar {
            get {
                return ResourceManager.GetString("IdCuentaEstandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string IdCuentaGratuita {
            get {
                return ResourceManager.GetString("IdCuentaGratuita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        public static string IdCuentaPremium {
            get {
                return ResourceManager.GetString("IdCuentaPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string IdEstadoCuentaActiva {
            get {
                return ResourceManager.GetString("IdEstadoCuentaActiva", resourceCulture);
            }
        }
    }
}
