//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validator() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PERFISOFT.VENTASPLATFORM.INFRASTRUCTURE.COMMON.Resource.Validator", typeof(Validator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} longitud del parámetro debe estar entre 2 y 100 caracteres.
        /// </summary>
        public static string PropertyNameCorrectLenght {
            get {
                return ResourceManager.GetString("PropertyNameCorrectLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} valor incorrecto.
        /// </summary>
        public static string PropertyNameCorrectValue {
            get {
                return ResourceManager.GetString("PropertyNameCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no tiene un email válido.
        /// </summary>
        public static string PropertyNameInvalidEmail {
            get {
                return ResourceManager.GetString("PropertyNameInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no tiene un formato de fecha válido.
        /// </summary>
        public static string PropertyNameInvalidFecha {
            get {
                return ResourceManager.GetString("PropertyNameInvalidFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no tiene un identificador válido.
        /// </summary>
        public static string PropertyNameInvalidGuid {
            get {
                return ResourceManager.GetString("PropertyNameInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no tiene una longitud valida.
        /// </summary>
        public static string PropertyNameInvalidLength {
            get {
                return ResourceManager.GetString("PropertyNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} No contiene la longitud de código correcta.
        /// </summary>
        public static string PropertyNameInvalidLengthOTP {
            get {
                return ResourceManager.GetString("PropertyNameInvalidLengthOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no tiene la edad requerida para poder continuar en nuestro sistema.
        /// </summary>
        public static string PropertyNameInvalidUserAge {
            get {
                return ResourceManager.GetString("PropertyNameInvalidUserAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} No cumple con la cantidad de digitos de una contraseña segura. Minimo 12 digitos..
        /// </summary>
        public static string PropertyNameLengthPassword {
            get {
                return ResourceManager.GetString("PropertyNameLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} debe incluir como máximo 80 caracteres.
        /// </summary>
        public static string PropertyNameMaxLengthPassword {
            get {
                return ResourceManager.GetString("PropertyNameMaxLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} debe incluir como máximo 40 caracteres.
        /// </summary>
        public static string PropertyNameMaxLengthUser {
            get {
                return ResourceManager.GetString("PropertyNameMaxLengthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} No cumple con la cantidad de digitos de un nombre de usuario seguro. Mínimo 12 digitos..
        /// </summary>
        public static string PropertyNameMinLengthUser {
            get {
                return ResourceManager.GetString("PropertyNameMinLengthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no debe contener números.
        /// </summary>
        public static string PropertyNameNoNumbers {
            get {
                return ResourceManager.GetString("PropertyNameNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no debe ser vacío.
        /// </summary>
        public static string PropertyNameNotEmpty {
            get {
                return ResourceManager.GetString("PropertyNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} no debe ser nulo.
        /// </summary>
        public static string PropertyNameNotNull {
            get {
                return ResourceManager.GetString("PropertyNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName] solo debe de contener letras, espacios, apóstrofos y guiones..
        /// </summary>
        public static string PropertyNameOnlyCharacters {
            get {
                return ResourceManager.GetString("PropertyNameOnlyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName] solo debe de contener números.
        /// </summary>
        public static string PropertyNameOnlyNumbers {
            get {
                return ResourceManager.GetString("PropertyNameOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PropertyName} debe incluir al menos una mayúscula, una minúscula, un número y un símbolo especial..
        /// </summary>
        public static string PropertyNameSecurePassword {
            get {
                return ResourceManager.GetString("PropertyNameSecurePassword", resourceCulture);
            }
        }
    }
}
